In [2]:
import numpy as np

In [4]:
a=np.array([1,2,3]) #rank=1인 어레이 (행렬이아닌 벡터)
print(a,type(a))
print(a.dtype)
print(a.shape) #?
print(a.size)
print(a.ndim) #차원

[1 2 3] <class 'numpy.ndarray'>
int64
(3,)
3
1


In [6]:
b=np.array([[1,2,3],[4,5,6.0]]) #rank=2인 어레이 (행렬)
print(b,'\n',b.shape)
print(b.size)
print(b.ndim)

[[1. 2. 3.]
 [4. 5. 6.]] 
 (2, 3)
6
2


In [9]:
a=np.array([[[1.5,2,3],[4,5,6]],[[3,1,6],[5,5,9]]]) #rank=3인 어레이
print(a,'\n',a.shape)

[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  1.  6. ]
  [5.  5.  9. ]]] 
 (2, 2, 3)


### special array

In [12]:
a=np.arange(6)
print(a)
print(a.shape)

[0 1 2 3 4 5]
(6,)


In [15]:
b=np.arange(7,11)
print(b)

[ 7  8  9 10]


In [17]:
c=np.arange(0,120,20) #20간격으로 0~120사이
print(c)

[  0  20  40  60  80 100]


In [19]:
d=np.arange(0.1,2,0.1)
print(d)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8
 1.9]


In [21]:
#linspace
pi=np.pi
a=np.linspace(0,2,9) #0부터 2사이에 숫자 9개. 등간격으로
print(a)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [23]:
b=np.linspace(0,2*pi,10)
print(b)

[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]


In [29]:
#special arrays
a=np.zeros((2,2)) *2*2를 다 0으로
print(a)
b=np.ones((1,2)) #1*2를 다 1로
print(b)
c=np.full((2,2),7) #2*2를 7로 다채움
print(c)
d=np.eye(2) #I
print(d)


[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]


### random numbers

In [31]:
a=np.random.rand(2,3)
print("a={}".format(a))

a=[[0.43014139 0.60452346 0.79754987]
 [0.18407854 0.51396759 0.42948569]]


In [32]:
#random seed - random number을 정해놓음 (분석할때많이씀)
np.random.seed(1)
a=np.random.rand(10)
print(a)

[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
 1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01
 3.96767474e-01 5.38816734e-01]


In [34]:
b=np.random.rand(10)
print(b)

[0.80074457 0.96826158 0.31342418 0.69232262 0.87638915 0.89460666
 0.08504421 0.03905478 0.16983042 0.8781425 ]


In [35]:
np.random.seed(1)
c=np.random.rand(10)
print(c)

[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
 1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01
 3.96767474e-01 5.38816734e-01]


In [36]:
#standard normal distribution
a=np.random.randn(5)
print(a)

[ 1.74481176 -0.7612069   0.3190391  -0.24937038  1.46210794]


In [38]:
#random integer
a=np.random.randint(0,3,(10,10)) #0~3사이 랜덤, 10*10 만들기
print(a)


[[0 1 0 2 1 2 0 0 2 2]
 [2 0 1 2 2 2 2 0 2 1]
 [1 2 0 2 0 2 1 1 1 2]
 [1 1 0 2 0 1 0 1 1 0]
 [1 1 1 2 1 0 0 2 1 0]
 [0 1 2 1 1 0 1 0 1 0]
 [1 1 1 1 0 2 1 0 0 2]
 [1 0 2 2 2 0 1 1 1 1]
 [2 0 0 2 0 1 0 2 0 2]
 [2 0 1 0 0 0 1 2 1 0]]


### exercise

In [43]:
a=5
b=12
ans=a+(b-a)*np.random.rand(10,)
print(ans)


[ 8.98196006  7.22153687 11.92031308  9.05821653  7.66098821  8.85663753
 10.21734102  9.68463025  6.8544369   5.46434384]


In [44]:
u=3
s=5

#(x-u)/s
x=u+s*np.random.rand(5,)
print(x)

[4.85042099 6.14858754 4.05087005 6.76377777 3.33268241]


### manipulations

In [46]:
#reshape
a=np.arange(6)
print(a,a.shape)

[0 1 2 3 4 5] (6,)


In [48]:
b=a.reshape(6,1) #6*1로
print(b)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [51]:
c=a.reshape(-1,2) #-1은 조커같이, 계산하기 싫을때 뒤에껄 2로 고정시키고, -1자리는 계산해줘!
print(c)

[[0 1 2]
 [3 4 5]]


In [53]:
#flatten - 원래대로 돌아가는것
e=a.reshape(2,3) #2*3으로
print(e,e.shape)

f=e.flatten()
print(f)

[[0 1 2]
 [3 4 5]] (2, 3)
[0 1 2 3 4 5]


In [62]:
a=np.linspace(0,10,11)
print(a,a.dtype)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] float64


In [55]:
b=a.astype(int) #type변환
print(b)
print(b.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10]
int64


### submatrix

In [64]:
a=np.arange(10) #1~10까지의 배열
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [65]:
print(a[1])
print(a[:2])
print(a[:-2])

print(a[1:9:3]) #1~9전까지 3씩 건너서
print(a[::2])

1
[0 1]
[0 1 2 3 4 5 6 7]
[1 4 7]
[0 2 4 6 8]


In [69]:
#dimension이 2이상일때도 비슷
a=np.arange(12).reshape(3,4) #3*4로 reshpae
print(a)

print(a[0,1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
1


In [70]:
b=a[1,:] #a의 두번째행
print(b)

[4 5 6 7]


In [72]:
c=a[1:3,:] #a의 두번째에서 세번째행
print(c)


[[ 4  5  6  7]
 [ 8  9 10 11]]


### change values

In [74]:
a=np.arange(10)
print(a)

a[0]=1000
print(a)
a[1:3]=np.array([-10,10])
print(a)

[0 1 2 3 4 5 6 7 8 9]
[1000    1    2    3    4    5    6    7    8    9]
[1000  -10   10    3    4    5    6    7    8    9]


### copy

In [76]:
a=np.arange(6)
b=a
c=a[:]
d=a.copy()

print(a,b,c,d)

[0 1 2 3 4 5] [0 1 2 3 4 5] [0 1 2 3 4 5] [0 1 2 3 4 5]


In [77]:
a[0]=100
print(a,b,c,d) #d는 바뀌는 값에 영향받지 않음

[100   1   2   3   4   5] [100   1   2   3   4   5] [100   1   2   3   4   5] [0 1 2 3 4 5]


In [78]:
b[0]=1000
print(a,b,c,d)

[1000    1    2    3    4    5] [1000    1    2    3    4    5] [1000    1    2    3    4    5] [0 1 2 3 4 5]


### basic operations

In [79]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

print(x.shape, y.shape)

(2, 2) (2, 2)


In [80]:
print(x+y)
print(np.add(x,y))
print(x-y)
print(np.subtract(x,y))
print(x*y)
print(np.multiply(x,y)) #element들끼리의 곱
print(x/y)
print(np.divide(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [81]:
#Elementwise function - np로 다양한 것 계산 가능
print(x**2,'\n',x**3)
print(np.sqrt(x))
print(np.exp(x))
print(np.sin(x))

[[ 1  4]
 [ 9 16]] 
 [[ 1  8]
 [27 64]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
[[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]


In [85]:
#sum, cumsum, min, max
F=np.arange(12).reshape(3,4)
print(F)

Fsum=F.sum()
FsumCol=F.sum(axis=0) #col sum
FsumRow=F.sum(axis=1) #row sum

print(Fsum,FsumCol,FsumRow)
print(np.sum(F)) #원소총합 =F.sum() = np.sum(F)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66 [12 15 18 21] [ 6 22 38]
66


In [86]:
Fcumsum=F.cumsum() # 누적합계
Fcumsum1=F.cumsum(axis=1) #행끼리 누적합계
print(Fcumsum,Fcumsum1)

[ 0  1  3  6 10 15 21 28 36 45 55 66] [[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [87]:
Fmin=F.min() # 전체원소 중 최솟값
Fmin1=F.min(axis=1) #행끼리 최솟값
print(Fmin,Fmin1)

0 [0 4 8]


In [89]:
Fmax=F.max() #전체원소 중 최댓값
Fmax0=F.max(axis=0) #열끼리 최댓값
print(Fmax,Fmax0)

11 [ 8  9 10 11]


In [96]:
#sort
a=np.array([[1,4],[3,1]])
print(a)

b=np.sort(a) # row내에서 sort
print(b)

c=np.sort(a,axis=None) #벡터로 전체 정렬
print(c)

d=np.sort(a,axis=0) #col내에서 sort (1이 default)
print(d)

[[1 4]
 [3 1]]
[[1 4]
 [1 3]]
[1 1 3 4]
[[1 1]
 [3 4]]


In [90]:
#transpose
a=np.arange(6).reshape(2,3)
print(a,a.shape)

b=a.T
print(b,b.shape)

[[0 1 2]
 [3 4 5]] (2, 3)
[[0 3]
 [1 4]
 [2 5]] (3, 2)


In [ ]:
#inner product & matrix product

In [ ]:
#broadcasting 