In [1]:
import numpy as np
import pandas as pd

In [ ]:
#numpy 는 행렬 / pandas는 dataframe

In [ ]:
#하나의 col이 series

In [2]:
pd.Series(np.random.randn(5)) #자연스럽게 index 생성

0    0.424233
1   -0.460867
2    2.051402
3    1.449950
4    0.453725
dtype: float64

In [6]:
s=pd.Series(np.random.randn(5), index=['a','b','c','d','e'])
print(s)

a   -2.365449
b    1.079782
c   -0.515810
d    0.346372
e   -1.853565
dtype: float64


In [10]:
cityNames=pd.Series(['Seoul','Busan','Incheon','수원'],index=['a','b','c','d'])
populations=pd.Series([100,300,120], index=['a','c','d'])

print(cityNames)
print(populations)

a      Seoul
b      Busan
c    Incheon
d         수원
dtype: object
a    100
c    300
d    120
dtype: int64


In [11]:
df=pd.DataFrame({'City Name':cityNames,
                'Population':populations})

print(df)

  City Name  Population
a     Seoul       100.0
b     Busan         NaN
c   Incheon       300.0
d        수원       120.0


In [12]:
df.head() #df 4줄까지 (여기서는 데이터가 작아서..)

City Name  Population
a     Seoul       100.0
b     Busan         NaN
c   Incheon       300.0
d        수원       120.0

In [13]:
df.head(2) #df 위에서 두줄

City Name  Population
a     Seoul       100.0
b     Busan         NaN

In [14]:
df.tail(2) #df 아래에서 두줄

City Name  Population
c   Incheon       300.0
d        수원       120.0

In [15]:
print(df.keys()) #colnames  = 기준

Index(['City Name', 'Population'], dtype='object')


In [16]:
print(df.keys()[0]) #첫번째 col

City Name


In [17]:
df.index #row

Index(['a', 'b', 'c', 'd'], dtype='object')

In [18]:
df.describe() #R summary 

Population
count    3.000000
mean   173.333333
std    110.151411
min    100.000000
25%    110.000000
50%    120.000000
75%    210.000000
max    300.000000

- example

In [19]:
np.random.seed(1)
a=np.random.randn(10,4) #10*4
print(a)

[[ 1.62434536 -0.61175641 -0.52817175 -1.07296862]
 [ 0.86540763 -2.3015387   1.74481176 -0.7612069 ]
 [ 0.3190391  -0.24937038  1.46210794 -2.06014071]
 [-0.3224172  -0.38405435  1.13376944 -1.09989127]
 [-0.17242821 -0.87785842  0.04221375  0.58281521]
 [-1.10061918  1.14472371  0.90159072  0.50249434]
 [ 0.90085595 -0.68372786 -0.12289023 -0.93576943]
 [-0.26788808  0.53035547 -0.69166075 -0.39675353]
 [-0.6871727  -0.84520564 -0.67124613 -0.0126646 ]
 [-1.11731035  0.2344157   1.65980218  0.74204416]]


In [21]:
dfA=pd.DataFrame(a)
print(dfA.head()) #4*4까지 보여줌
print(dfA.describe())

          0         1         2         3
0  1.624345 -0.611756 -0.528172 -1.072969
1  0.865408 -2.301539  1.744812 -0.761207
2  0.319039 -0.249370  1.462108 -2.060141
3 -0.322417 -0.384054  1.133769 -1.099891
4 -0.172428 -0.877858  0.042214  0.582815
               0          1          2          3
count  10.000000  10.000000  10.000000  10.000000
mean    0.004181  -0.404402   0.493033  -0.451204
std     0.909089   0.933614   0.990475   0.902147
min    -1.117310  -2.301539  -0.691661  -2.060141
25%    -0.595984  -0.804836  -0.426851  -1.038669
50%    -0.220158  -0.497905   0.471902  -0.578980
75%     0.728815   0.113469   1.380023   0.373705
max     1.624345   1.144724   1.744812   0.742044


### accessing and Manuplating Data

In [48]:
cityNames=pd.Series(['Seoul','Busan','Incheon','수원'])
populations=pd.Series([100,300,120])

cities=pd.DataFrame({'City name': cityNames,
                     'Population':populations})

In [49]:
cities.head()

City name  Population
0     Seoul       100.0
1     Busan       300.0
2   Incheon       120.0
3        수원         NaN

In [50]:
print(cities[0:2]) #처음 두개 데이터

  City name  Population
0     Seoul       100.0
1     Busan       300.0


In [51]:
cities.index

RangeIndex(start=0, stop=4, step=1)

In [52]:
v=cities.values
print(v,type(v))

[['Seoul' 100.0]
 ['Busan' 300.0]
 ['Incheon' 120.0]
 ['수원' nan]] <class 'numpy.ndarray'>


In [53]:
print(v[0])
print(v[:,0]) #0번째 열의 모든 행

['Seoul' 100.0]
['Seoul' 'Busan' 'Incheon' '수원']


In [54]:
#adding a series to the DataFrame
cities['Area square km']=pd.Series([600,765,1000,121])
print(cities)

  City name  Population  Area square km
0     Seoul       100.0             600
1     Busan       300.0             765
2   Incheon       120.0            1000
3        수원         NaN             121


In [55]:
cities['Population density']=cities['Population']/cities['Area square km']
print(cities)

  City name  Population  Area square km  Population density
0     Seoul       100.0             600            0.166667
1     Busan       300.0             765            0.392157
2   Incheon       120.0            1000            0.120000
3        수원         NaN             121                 NaN


In [56]:
cities=cities.drop('Population',axis=1) #col방향으로 population x (0=col)
print(cities)

  City name  Area square km  Population density
0     Seoul             600            0.166667
1     Busan             765            0.392157
2   Incheon            1000            0.120000
3        수원             121                 NaN


In [58]:
cities['Population']=populations #다시
print(cities)

  City name  Area square km  Population density  Population
0     Seoul             600            0.166667       100.0
1     Busan             765            0.392157       300.0
2   Incheon            1000            0.120000       120.0
3        수원             121                 NaN         NaN


### Saving Data to csv file

In [23]:
dfA.to_csv('testA.csv')
dfA.to_csv('testB.csv', index=False) # 행넘버없이

### loading csv file

In [3]:
import pandas as pd
import numpy as np

df=pd.read_csv("testA.csv",sep=",")
df

Unnamed: 0         0         1         2         3
0           0  1.624345 -0.611756 -0.528172 -1.072969
1           1  0.865408 -2.301539  1.744812 -0.761207
2           2  0.319039 -0.249370  1.462108 -2.060141
3           3 -0.322417 -0.384054  1.133769 -1.099891
4           4 -0.172428 -0.877858  0.042214  0.582815
5           5 -1.100619  1.144724  0.901591  0.502494
6           6  0.900856 -0.683728 -0.122890 -0.935769
7           7 -0.267888  0.530355 -0.691661 -0.396754
8           8 -0.687173 -0.845206 -0.671246 -0.012665
9           9 -1.117310  0.234416  1.659802  0.742044

In [6]:
data=df.values #안에 값들만. 행렬처럼
print(data)


[[ 0.          1.62434536 -0.61175641 -0.52817175 -1.07296862]
 [ 1.          0.86540763 -2.3015387   1.74481176 -0.7612069 ]
 [ 2.          0.3190391  -0.24937038  1.46210794 -2.06014071]
 [ 3.         -0.3224172  -0.38405435  1.13376944 -1.09989127]
 [ 4.         -0.17242821 -0.87785842  0.04221375  0.58281521]
 [ 5.         -1.10061918  1.14472371  0.90159072  0.50249434]
 [ 6.          0.90085595 -0.68372786 -0.12289023 -0.93576943]
 [ 7.         -0.26788808  0.53035547 -0.69166075 -0.39675353]
 [ 8.         -0.6871727  -0.84520564 -0.67124613 -0.0126646 ]
 [ 9.         -1.11731035  0.2344157   1.65980218  0.74204416]]


dtype('float64')