In [6]:
import numpy as np
import tensorflow as tf

In [2]:
#Xor data
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y=np.array([[0],[1],[1],[0]])

### Deep Learning (one hidden layer)
- from 정석으로 배우는 딥러닝

In [3]:
#Model
tf.set_random_seed(1234)
in_dim=2
x=tf.placeholder(tf.float32,shape=[None,in_dim]) #input 2개
t=tf.placeholder(tf.float32,shape=[None,1])

#input layer-hidden layer
W=tf.Variable(tf.truncated_normal([in_dim,2], seed=0)) 
#
b=tf.Variable(tf.zeros([2])) #(0,0), 2rㅐ
h=tf.nn.sigmoid(tf.matmul(x,W)+b)

#hidden layer-output layer
V=tf.Variable(tf.truncated_normal([in_dim,1],seed=23))
c=tf.Variable(tf.zeros([1])) #(0)
y=tf.nn.sigmoid(tf.matmul(h,V)+c)

#loss function
cross_entropy=-tf.reduce_mean(t*tf.log(y)+(1-t)*tf.log(1-y))

#optimizer
lr=0.1
optimizer=tf.train.GradientDescentOptimizer(lr)
train_step=optimizer.minimize(cross_entropy)

#evaluation
correct_prediction=tf.equal(tf.to_float(tf.greater(y,0.5)),t)


In [4]:
#Initialize

init=tf.global_variables_initializer()
sess=tf.Session()
sess.run(init)

print('W=', sess.run(W))
print('V=',sess.run(V))

W= [[-0.30200204  1.9954948 ]
 [-1.4346613   0.05055132]]
V= [[-1.3118125 ]
 [ 0.15874536]]


In [5]:
#Learning
for epoch in range(8000):
    sess.run(train_step, feed_dict={
        x:X,
        t:Y
    })
    if epoch % 1000==0:
        print('epoch:', epoch)

epoch: 0
epoch: 1000
epoch: 2000
epoch: 3000
epoch: 4000
epoch: 5000
epoch: 6000
epoch: 7000


In [6]:
# 결과확인
classified=correct_prediction.eval(session=sess, feed_dict={
    x:X,
    t:Y
})
prob=y.eval(session=sess, feed_dict={
    x:X
})

print('classified:',classified)
print('output probability:', prob)

classified: [[ True]
 [ True]
 [ True]
 [ True]]
output probability: [[0.01746599]
 [0.97482604]
 [0.9751473 ]
 [0.02449046]]


In [7]:
sess.close()


### Multi-Class Classification(IRIS)

In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [2]:
iris=load_iris()

print(iris.keys())
print(iris['DESCR'])

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])
Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ==

In [3]:
x=iris.data
y=iris.target
target_names=iris.target_names
print(x)
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [4]:
X_train, X_test, y_train, y_test = train_test_split(x,y,random_state=10, test_size=0.25)

print(X_train.shape)
print(y_train.shape)

(112, 4)
(112,)


- change formation for output(multi-class classfication)

In [7]:
count_train=np.bincount(y_train)
print(count_train) #0:39, 1:35, 2:38                                                                                               

[39 35 38]


In [8]:
Y_train=np.eye(3)[y_train].astype(int) #target identity matrix로 바꾸는 과정
Y_test=np.eye(3)[y_test].astype(int)


print(X_train.shape, Y_train.shape)

(112, 4) (112, 3)


In [13]:
inDim=4 #'data', 'target', 'target_names','feature_names']
outDim=3 #0,1,2

In [15]:
#Model

hiddenDim=10

tf.set_random_seed(1234)

x=tf.placeholder(tf.float32, shape=[None,inDim])
t=tf.placeholder(tf.float32, shape=[None,outDim])

#input layer-hidden layer
W=tf.Variable(tf.truncated_normal([inDim, hiddenDim],seed=0))
b=tf.Variable(tf.zeros([hiddenDim])) #0~0.1사이의 작은값
h=tf.nn.softmax(tf.matmul(x,W)+b)

#hidden layer-output layer
V=tf.Variable(tf.truncated_normal([hiddenDim,outDim],seed=23))
c=tf.Variable(tf.zeros([outDim]))
y=tf.nn.softmax(tf.matmul(h,V)+c)

#Loss function
cross_entropy=-tf.reduce_mean(tf.reduce_sum(t*tf.log(y),reduction_indices=[1])) #reduce sum 하는 축

#traning
lr=0.05 #learning rate
optimizer=tf.train.GradientDescentOptimizer(lr)
train_step=optimizer.minimize(cross_entropy)

#evaluation
correct_prediction=tf.equal(tf.argmax(y,1), tf.argmax(t,1)) #argmax:결과 값중 최댓값의 인덱스를 얻을 때
accuracy=tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
              


In [28]:
#initialize all variables

init=tf.global_variables_initializer()
sess=tf.Session()
sess.run(init)

In [17]:
#Before training
loss_train=cross_entropy.eval(session=sess, feed_dict={
    x:X_train, 
    t:Y_train
})

accuracy_train=accuracy.eval(session=sess, feed_dict={x:X_train, t:Y_train})

print("train_set loss=",loss_train,
     ",train_set accuracy=", accuracy_train)

train_set loss= 1.3322313 ,train_set accuracy= 0.3392857


In [29]:
#Training

n_epoch=1000

for epoch in range(n_epoch):
    sess.run(train_step, feed_dict={
        x:X_train,
        t:Y_train
    })
    if epoch % 100==0:
        loss_train=cross_entropy.eval(session=sess,feed_dict={
            x:X_train,
            t:Y_train
        })
        
        accurcy_train=accuracy.eval(session=sess, feed_dict={
            x:X_train,
            t:Y_train
        })
        
        print('epoch:', epoch,
             'loss of training set=',loss_train,
             "accuracy of training set=",accuracy_train)

epoch: 0 loss of training set= 1.3222893 accuracy of training set= 0.3482143
epoch: 1000 loss of training set= 1.0975782 accuracy of training set= 0.3482143
epoch: 2000 loss of training set= 1.0975776 accuracy of training set= 0.3482143
epoch: 3000 loss of training set= 1.097577 accuracy of training set= 0.3482143
epoch: 4000 loss of training set= 1.0975764 accuracy of training set= 0.3482143
epoch: 5000 loss of training set= 1.097576 accuracy of training set= 0.3482143
epoch: 6000 loss of training set= 1.0975755 accuracy of training set= 0.3482143
epoch: 7000 loss of training set= 1.0975751 accuracy of training set= 0.3482143
epoch: 8000 loss of training set= 1.0975748 accuracy of training set= 0.3482143
epoch: 9000 loss of training set= 1.0975745 accuracy of training set= 0.3482143


In [30]:
#For Train set
loss_train=cross_entropy.eval(session=sess, feed_dict={
    x:X_train,
    t:Y_train
})
accuracy_train=accuracy.eval(session=sess, feed_dict={
    x:X_train,
    t:Y_train
})

print("train_set loss=",loss_train,
      ", train_set accuracy=",accuracy_train)

#y_val_train=y.eval(session=sess, feed_dict={
#    x:X_train,
#    t:Y_train
#})
#print(y_val_train)

classified=correct_prediction.eval(session=sess, feed_dict={x:X_train, t:Y_train})

print(classified)





train_set loss= 1.0975741 , train_set accuracy= 0.3482143
[False False  True  True False  True False  True False False False False
 False False False False False  True  True False  True False  True  True
 False False False  True False  True False False  True False False False
 False False  True False False False  True False False False  True  True
  True False False False False  True  True  True False False False False
 False False False False False  True  True False  True  True False False
  True  True  True False  True False  True False False  True False False
 False  True False  True False False False False  True False False False
 False False False  True False  True  True False  True False False False
 False  True False  True]


In [31]:
#For the test set
loss_test=cross_entropy.eval(session=sess, feed_dict={x:X_test, t:Y_test})
accuracy_test=accuracy.eval(session=sess, feed_dict={x:X_test, t:Y_test})
print("test_set loss=", loss_test,
      ",test_set accuracy", accuracy_test)

#y_val_test=y.eval(session=sess, feed_dict={
#    x:X_test,
#    t:Y_test
#})
#print(y_val_test)

classified=correct_prediction.eval(session=sess,feed_dict={x:X_test,t:Y_test})
print(classified)

test_set loss= 1.105864 ,test_set accuracy 0.28947368
[False False  True False  True False False False  True False False False
 False  True  True False False  True  True  True False False False  True
 False  True False False False False False False False False False  True
 False False]


In [26]:
sess.close()